#!/bin/bash

dateTAG="submitted_`date +%Y_%m_%d_%H_%M`"

# No Neutron Reweight Jobs
#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=4200MB --disk=4GB --expected-lifetime=12h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_CCQENu_tracker_${dateTAG}_MnvTune_v2_noNeutRwgt_noNeutronCuts_wSYSTEMATICS -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_NewIO_NoNeutronReweight.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh CCQENu_playlist_6A_data.txt CCQENu_playlist_6A_tracker.txt 0 2 Tracker "noNeutCuts" 0

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=4200MB --disk=4GB --expected-lifetime=12h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_CCQENu_tracker_${dateTAG}_MnvTune_v2_noNeutRwgt_wNeutronCuts_wSYSTEMATICS -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_NewIO_NoNeutronReweight.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh CCQENu_playlist_6A_data.txt CCQENu_playlist_6A_tracker.txt 0 2 Tracker

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=4200MB --disk=4GB --expected-lifetime=12h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_CCQENu_tracker_${dateTAG}_MnvTune_v1_noNeutRwgt_noNeutronCuts_wSYSTEMATICS -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_NewIO_NoNeutronReweight.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh CCQENu_playlist_6A_data.txt CCQENu_playlist_6A_tracker.txt 0 1 Tracker "noNeutCuts" 0

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=4200MB --disk=4GB --expected-lifetime=12h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_CCQENu_tracker_${dateTAG}_MnvTune_v1_noNeutRwgt_wNeutronCuts_wSYSTEMATICS -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_NewIO_NoNeutronReweight.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh CCQENu_playlist_6A_data.txt CCQENu_playlist_6A_tracker.txt 0 1 Tracker

# Yes Neutron Reweight Jobs
#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=2400MB --disk=2GB --expected-lifetime=3h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_CCQENu_tracker_${dateTAG}_MnvTune_v2_noNeutronCuts_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_MichelSB.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh CCQENu_playlist_6A_data.txt CCQENu_playlist_6A_tracker.txt 1 2 Tracker "\"noNeutCuts\"" 0

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=2400MB --disk=2GB --expected-lifetime=3h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_CCQENu_tracker_${dateTAG}_MnvTune_v2_wNeutronCuts_neutKE_10_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_MichelSB.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh CCQENu_playlist_6A_data.txt CCQENu_playlist_6A_tracker.txt 1 2 Tracker

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=2400MB --disk=2GB --expected-lifetime=3h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_CCQENu_tracker_${dateTAG}_MnvTune_v2_wNeutronCuts_neutKE_100_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_NeutKE.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh CCQENu_playlist_6A_data.txt CCQENu_playlist_6A_tracker.txt 1 2 Tracker "NONE" 100.0

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=2400MB --disk=2GB --expected-lifetime=3h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_CCQENu_tracker_${dateTAG}_MnvTune_v2_wNeutronCuts_neutKE_50_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_NeutKE.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh CCQENu_playlist_6A_data.txt CCQENu_playlist_6A_tracker.txt 1 2 Tracker "NONE" 50.0

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=2400MB --disk=2GB --expected-lifetime=3h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_CCQENu_tracker_${dateTAG}_MnvTune_v2_wNeutronCuts_neutKE_0.001_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_NeutKE.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh CCQENu_playlist_6A_data.txt CCQENu_playlist_6A_tracker.txt 1 2 Tracker "NONE" 0.001

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=2400MB --disk=2GB --expected-lifetime=3h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_CCQENu_tracker_${dateTAG}_MnvTune_v1_noNeutronCuts_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_MichelSB.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh CCQENu_playlist_6A_data.txt CCQENu_playlist_6A_tracker.txt 1 1 Tracker "\"noNeutCuts"\" 0

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=2400MB --disk=2GB --expected-lifetime=3h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_CCQENu_tracker_${dateTAG}_MnvTune_v1_wNeutronCuts_neutKE_10_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_MichelSB.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh CCQENu_playlist_6A_data.txt CCQENu_playlist_6A_tracker.txt 1 1 Tracker

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=2400MB --disk=2GB --expected-lifetime=3h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_CCQENu_tracker_${dateTAG}_MnvTune_v1_wNeutronCuts_neutKE_100_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_NeutKE.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh CCQENu_playlist_6A_data.txt CCQENu_playlist_6A_tracker.txt 1 1 Tracker "NONE" 100.0

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=2400MB --disk=2GB --expected-lifetime=3h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_CCQENu_tracker_${dateTAG}_MnvTune_v1_wNeutronCuts_neutKE_50_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_NeutKE.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh CCQENu_playlist_6A_data.txt CCQENu_playlist_6A_tracker.txt 1 1 Tracker "NONE" 50.0

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=2400MB --disk=2GB --expected-lifetime=3h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_CCQENu_tracker_${dateTAG}_MnvTune_v1_wNeutronCuts_neutKE_0.001_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_NeutKE.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh CCQENu_playlist_6A_data.txt CCQENu_playlist_6A_tracker.txt 1 1 Tracker "NONE" 0.001

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=2400MB --disk=2GB --expected-lifetime=3h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_CCQENu_tracker_${dateTAG}_MnvTune_v2_RecoilSB_noNeutronCuts_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_RecoilSB_20220207.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh CCQENu_playlist_6A_data.txt CCQENu_playlist_6A_tracker.txt 1 2 Tracker "\"noNeutCuts\"" 0

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=2400MB --disk=2GB --expected-lifetime=3h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_CCQENu_tracker_${dateTAG}_MnvTune_v2_RecoilSB_wNeutronCuts_neutKE_10_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_RecoilSB_20220207.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh CCQENu_playlist_6A_data.txt CCQENu_playlist_6A_tracker.txt 1 2 Tracker

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=2400MB --disk=2GB --expected-lifetime=3h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_CCQENu_tracker_${dateTAG}_MnvTune_v1_RecoilSB_noNeutronCuts_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_RecoilSB_20220207.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh CCQENu_playlist_6A_data.txt CCQENu_playlist_6A_tracker.txt 1 1 Tracker "\"noNeutCuts\"" 0

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=2400MB --disk=2GB --expected-lifetime=3h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_CCQENu_tracker_${dateTAG}_MnvTune_v1_RecoilSB_wNeutronCuts_neutKE_10_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_RecoilSB_20220207.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh CCQENu_playlist_6A_data.txt CCQENu_playlist_6A_tracker.txt 1 1 Tracker

###jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=5600MB --disk=4GB --expected-lifetime=15h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_CCQENu_tracker_${dateTAG}_MnvTune_v2_RecoilSB_noNeutronCuts_wSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_RecoilSB_20220207.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh CCQENu_playlist_6A_data.txt CCQENu_playlist_6A_tracker.txt 0 2 Tracker "\"noNeutCuts\"" 0

###jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=5600MB --disk=4GB --expected-lifetime=15h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_CCQENu_tracker_${dateTAG}_MnvTune_v2_RecoilSB_wNeutronCuts_neutKE_10_wSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_RecoilSB_20220207.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh CCQENu_playlist_6A_data.txt CCQENu_playlist_6A_tracker.txt 0 2 Tracker

###jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=5600MB --disk=4GB --expected-lifetime=15h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_CCQENu_tracker_${dateTAG}_MnvTune_v1_RecoilSB_noNeutronCuts_wSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_RecoilSB_20220207.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh CCQENu_playlist_6A_data.txt CCQENu_playlist_6A_tracker.txt 0 1 Tracker "\"noNeutCuts\"" 0

###jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=5600MB --disk=4GB --expected-lifetime=15h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_CCQENu_tracker_${dateTAG}_MnvTune_v1_RecoilSB_wNeutronCuts_neutKE_10_wSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_RecoilSB_20220207.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh CCQENu_playlist_6A_data.txt CCQENu_playlist_6A_tracker.txt 0 1 Tracker

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=2400MB --disk=2GB --expected-lifetime=4h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_MAD_nuke_${dateTAG}_MnvTune_v2_RecoilSB_noNeutronCuts_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_RecoilSB_20220204.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh playlist_6A_data_Sept_2021_merged.txt playlist_6A_nuke_runs_126000_126100_June_2021_merged.txt 1 2 Targets "\"noNeutCuts\"" 0

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=2400MB --disk=2GB --expected-lifetime=4h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_MAD_nuke_${dateTAG}_MnvTune_v2_RecoilSB_wNeutronCuts_neutKE_10_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_RecoilSB_20220204.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh playlist_6A_data_Sept_2021_merged.txt playlist_6A_nuke_runs_126000_126100_June_2021_merged.txt 1 2 Targets

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=2400MB --disk=2GB --expected-lifetime=4h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_MAD_nuke_${dateTAG}_MnvTune_v1_RecoilSB_noNeutronCuts_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_RecoilSB_20220204.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh playlist_6A_data_Sept_2021_merged.txt playlist_6A_nuke_runs_126000_126100_June_2021_merged.txt 1 1 Targets "\"noNeutCuts\"" 0

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=2400MB --disk=2GB --expected-lifetime=4h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_MAD_nuke_${dateTAG}_MnvTune_v1_RecoilSB_wNeutronCuts_neutKE_10_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_RecoilSB_20220204.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh playlist_6A_data_Sept_2021_merged.txt playlist_6A_nuke_runs_126000_126100_June_2021_merged.txt 1 1 Targets

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=2400MB --disk=2GB --expected-lifetime=5h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_MAD_tracker_${dateTAG}_MnvTune_v2_RecoilSB_noNeutronCuts_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_RecoilSB_20220204.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh playlist_6A_data_Sept_2021_merged.txt playlist_6A_tracker_Sept_2021_merged.txt 1 2 Tracker "\"noNeutCuts\"" 0

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=2400MB --disk=2GB --expected-lifetime=5h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_MAD_tracker_${dateTAG}_MnvTune_v2_RecoilSB_wNeutronCuts_neutKE_10_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_RecoilSB_20220204.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh playlist_6A_data_Sept_2021_merged.txt playlist_6A_tracker_Sept_2021_merged.txt 1 2 Tracker

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=2400MB --disk=2GB --expected-lifetime=5h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_MAD_tracker_${dateTAG}_MnvTune_v1_RecoilSB_noNeutronCuts_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_RecoilSB_20220204.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh playlist_6A_data_Sept_2021_merged.txt playlist_6A_tracker_Sept_2021_merged.txt 1 1 Tracker "\"noNeutCuts\"" 0

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=2400MB --disk=2GB --expected-lifetime=5h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_MAD_tracker_${dateTAG}_MnvTune_v1_RecoilSB_wNeutronCuts_neutKE_10_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_RecoilSB_20220204.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh playlist_6A_data_Sept_2021_merged.txt playlist_6A_tracker_Sept_2021_merged.txt 1 1 Tracker

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=2400MB --disk=2GB --expected-lifetime=5h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_CCQENu_tracker_${dateTAG}_MnvTune_v2_noRecoil_wNeutronCuts_neutKE_10_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_NoRecoil_03052022.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh CCQENu_playlist_6A_data.txt CCQENu_playlist_6A_tracker.txt 1 2 Tracker

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=2400MB --disk=2GB --expected-lifetime=5h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_CCQENu_tracker_${dateTAG}_MnvTune_v1_noRecoil_wNeutronCuts_neutKE_10_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_NoRecoil_03052022.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh CCQENu_playlist_6A_data.txt CCQENu_playlist_6A_tracker.txt 1 1 Tracker

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=4GB --disk=4GB --expected-lifetime=6h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_CCQENu_tracker_${dateTAG}_MnvTune_v2_2DRecoil_ExtraDump_wNeutronCuts_neutKE_10_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_2DRecoil_ExtraDump_03082022.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh CCQENu_playlist_6A_data.txt CCQENu_playlist_6A_tracker.txt 1 2 Tracker

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=4GB --disk=4GB --expected-lifetime=6h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_CCQENu_tracker_${dateTAG}_MnvTune_v1_2DRecoil_ExtraDump_wNeutronCuts_neutKE_10_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_2DRecoil_ExtraDump_03082022.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh CCQENu_playlist_6A_data.txt CCQENu_playlist_6A_tracker.txt 1 1 Tracker

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=4GB --disk=4GB --expected-lifetime=6h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_CCQENu_tracker_${dateTAG}_MnvTune_v2_2DRecoil_ExtraDump_noNeutronCuts_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_2DRecoil_ExtraDump_03082022.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh CCQENu_playlist_6A_data.txt CCQENu_playlist_6A_tracker.txt 1 2 Tracker "\"noNeutCuts\"" 0

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=4GB --disk=4GB --expected-lifetime=6h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_CCQENu_tracker_${dateTAG}_MnvTune_v1_2DRecoil_ExtraDump_noNeutronCuts_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_2DRecoil_ExtraDump_03082022.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh CCQENu_playlist_6A_data.txt CCQENu_playlist_6A_tracker.txt 1 1 Tracker "\"noNeutCuts\"" 0

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=15GB --disk=5GB --expected-lifetime=18h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_CCQENu_tracker_${dateTAG}_MnvTune_v2_100MeVRecoilSB_wNeutronCuts_neutKE_10_wSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_RecoilSB_03222022.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh CCQENu_playlist_6A_data.txt CCQENu_playlist_6A_tracker.txt 0 2 Tracker

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=15GB --disk=5GB --expected-lifetime=18h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_CCQENu_tracker_${dateTAG}_MnvTune_v1_100MeVRecoilSB_wNeutronCuts_neutKE_10_wSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_RecoilSB_03222022.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh CCQENu_playlist_6A_data.txt CCQENu_playlist_6A_tracker.txt 0 1 Tracker

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=15GB --disk=5GB --expected-lifetime=18h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_CCQENu_tracker_${dateTAG}_MnvTune_v2_100MeVRecoilSB_noNeutronCuts_wSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_RecoilSB_03222022.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh CCQENu_playlist_6A_data.txt CCQENu_playlist_6A_tracker.txt 0 2 Tracker "\"noNeutCuts\"" 0

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=15GB --disk=5GB --expected-lifetime=18h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_CCQENu_tracker_${dateTAG}_MnvTune_v1_100MeVRecoilSB_noNeutronCuts_wSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_RecoilSB_03222022.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh CCQENu_playlist_6A_data.txt CCQENu_playlist_6A_tracker.txt 0 1 Tracker "\"noNeutCuts\"" 0

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=4GB --disk=4GB --expected-lifetime=4h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_CCQENu_tracker_${dateTAG}_MnvTune_v2_100MeVRecoilSB_wNeutronCuts_neutKE_10_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_RecoilSB_03222022.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh CCQENu_playlist_6A_data.txt CCQENu_playlist_6A_tracker.txt 1 2 Tracker

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=4GB --disk=4GB --expected-lifetime=4h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_CCQENu_tracker_${dateTAG}_MnvTune_v1_100MeVRecoilSB_wNeutronCuts_neutKE_10_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_RecoilSB_03222022.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh CCQENu_playlist_6A_data.txt CCQENu_playlist_6A_tracker.txt 1 1 Tracker

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=4GB --disk=4GB --expected-lifetime=4h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_CCQENu_tracker_${dateTAG}_MnvTune_v2_100MeVRecoilSB_noNeutronCuts_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_RecoilSB_03222022.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh CCQENu_playlist_6A_data.txt CCQENu_playlist_6A_tracker.txt 1 2 Tracker "\"noNeutCuts\"" 0

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=4GB --disk=4GB --expected-lifetime=4h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_CCQENu_tracker_${dateTAG}_MnvTune_v1_100MeVRecoilSB_noNeutronCuts_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_RecoilSB_03222022.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh CCQENu_playlist_6A_data.txt CCQENu_playlist_6A_tracker.txt 1 1 Tracker "\"noNeutCuts\"" 0

#i=1
#while [ $i -ne $((500/10+1)) ]
#do
#    KEthresh=$(($i*10))
    #echo /pnfs/minerva/scratch/users/dlast/MyANA_CCQENu_tracker_${dateTAG}_MnvTune_v1_2DRecoil_ExtraDump_wNeutronCuts_neutKE_${KEthresh}_noSYST
    #jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=4GB --disk=4GB --expected-lifetime=3h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_CCQENu_tracker_${dateTAG}_MnvTune_v1_2DRecoil_ExtraDump_wNeutronCuts_neutKE_${KEthresh}_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_2DRecoil_ExtraDump_03082022.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh CCQENu_playlist_6A_data.txt CCQENu_playlist_6A_tracker.txt 1 1 Tracker "\"NeutKEExploration\"" $KEthresh
#    i=$(($i+1))
#done

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=4GB --disk=4GB --expected-lifetime=6h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_CCQENu_tracker_${dateTAG}_MnvTune_v1_2DRecoil_ExtraDump_noNeutronCuts_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_2DRecoil_ExtraDump_03082022.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh CCQENu_playlist_6A_data.txt CCQENu_playlist_6A_tracker.txt 1 1 Tracker "\"noNeutCuts\"" 0

#### 17 degree business ####
#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=4GB --disk=4GB --expected-lifetime=4h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_CCQENu_tracker_${dateTAG}_MnvTune_v2_PreRecoil_17degree_wNeutronCuts_neutKE_10_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_PreRecoil_17degree_04042022.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh CCQENu_playlist_6A_data.txt CCQENu_playlist_6A_tracker.txt 1 2 Tracker

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=4GB --disk=4GB --expected-lifetime=4h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_CCQENu_tracker_${dateTAG}_MnvTune_v1_PreRecoil_17degree_wNeutronCuts_neutKE_10_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_PreRecoil_17degree_04042022.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh CCQENu_playlist_6A_data.txt CCQENu_playlist_6A_tracker.txt 1 1 Tracker

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=4GB --disk=4GB --expected-lifetime=4h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_CCQENu_tracker_${dateTAG}_MnvTune_v2_PreRecoil_17degree_noNeutronCuts_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_PreRecoil_17degree_04042022.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh CCQENu_playlist_6A_data.txt CCQENu_playlist_6A_tracker.txt 1 2 Tracker "\"noNeutCuts\"" 0

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=4GB --disk=4GB --expected-lifetime=4h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_CCQENu_tracker_${dateTAG}_MnvTune_v1_PreRecoil_17degree_noNeutronCuts_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_PreRecoil_17degree_04042022.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh CCQENu_playlist_6A_data.txt CCQENu_playlist_6A_tracker.txt 1 1 Tracker "\"noNeutCuts\"" 0

### Added Target Breakdowns ###
#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=5GB --disk=10GB --expected-lifetime=8h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_MAD_nuke_${dateTAG}_MnvTune_v2_TgtID_noNeutronCuts_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_TgtID_04282022.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh playlist_6A_data_Sept_2021_merged.txt playlist_6A_nuke_runs_126000_126100_June_2021_merged.txt 1 2 Targets "\"noNeutCuts\"" 0

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=5GB --disk=10GB --expected-lifetime=8h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_MAD_nuke_${dateTAG}_MnvTune_v2_TgtID_wNeutronCuts_neutKE_10_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_TgtID_04282022.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh playlist_6A_data_Sept_2021_merged.txt playlist_6A_nuke_runs_126000_126100_June_2021_merged.txt 1 2 Targets

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=5GB --disk=10GB --expected-lifetime=8h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_MAD_nuke_${dateTAG}_MnvTune_v1_TgtID_noNeutronCuts_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_TgtID_04282022.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh playlist_6A_data_Sept_2021_merged.txt playlist_6A_nuke_runs_126000_126100_June_2021_merged.txt 1 1 Targets "\"noNeutCuts\"" 0

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=5GB --disk=10GB --expected-lifetime=8h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_MAD_nuke_${dateTAG}_MnvTune_v1_TgtID_wNeutronCuts_neutKE_10_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_TgtID_04282022.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh playlist_6A_data_Sept_2021_merged.txt playlist_6A_nuke_runs_126000_126100_June_2021_merged.txt 1 1 Targets

###### P1 Check ######
#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=4GB --disk=4GB --expected-lifetime=4h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_MAD_tracker_${dateTAG}_MnvTune_v2_PreRecoil_17degree_wNeutronCuts_neutKE_10_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_TgtID_05112022.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh P1_playlist_6A_data.txt P1_playlist_6A_tracker.txt 1 2 Tracker

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=4GB --disk=4GB --expected-lifetime=4h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_MAD_tracker_${dateTAG}_MnvTune_v1_PreRecoil_17degree_wNeutronCuts_neutKE_10_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_TgtID_05112022.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh P1_playlist_6A_data.txt P1_playlist_6A_tracker.txt 1 1 Tracker

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=4GB --disk=4GB --expected-lifetime=4h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_MAD_tracker_${dateTAG}_MnvTune_v2_PreRecoil_17degree_noNeutronCuts_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_TgtID_05112022.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh P1_playlist_6A_data.txt P1_playlist_6A_tracker.txt 1 2 Tracker "\"noNeutCuts\"" 0

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=4GB --disk=4GB --expected-lifetime=4h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_MAD_tracker_${dateTAG}_MnvTune_v1_PreRecoil_17degree_noNeutronCuts_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_TgtID_05112022.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh P1_playlist_6A_data.txt P1_playlist_6A_tracker.txt 1 1 Tracker "\"noNeutCuts\"" 0

### Added Plastic/Water Separation ###
#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=5GB --disk=10GB --expected-lifetime=8h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_MAD_nuke_${dateTAG}_MnvTune_v2_TrueTgtID_noNeutronCuts_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_TrueTgtID_05252022.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh playlist_6A_data_Sept_2021_merged.txt playlist_6A_nuke_runs_126000_126100_June_2021_merged.txt 1 2 Targets "\"noNeutCuts\"" 0

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=5GB --disk=10GB --expected-lifetime=8h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_MAD_nuke_${dateTAG}_MnvTune_v2_TrueTgtID_wNeutronCuts_neutKE_10_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_TrueTgtID_05252022.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh playlist_6A_data_Sept_2021_merged.txt playlist_6A_nuke_runs_126000_126100_June_2021_merged.txt 1 2 Targets

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=5GB --disk=10GB --expected-lifetime=8h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_MAD_nuke_${dateTAG}_MnvTune_v1_TrueTgtID_noNeutronCuts_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_TrueTgtID_05252022.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh playlist_6A_data_Sept_2021_merged.txt playlist_6A_nuke_runs_126000_126100_June_2021_merged.txt 1 1 Targets "\"noNeutCuts\"" 0

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=5GB --disk=10GB --expected-lifetime=8h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_MAD_nuke_${dateTAG}_MnvTune_v1_TrueTgtID_wNeutronCuts_neutKE_10_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_TrueTgtID_05252022.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh playlist_6A_data_Sept_2021_merged.txt playlist_6A_nuke_runs_126000_126100_June_2021_merged.txt 1 1 Targets

### Added Plastic/Water Separation AND VTX binning fix ###
#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=6GB --disk=10GB --expected-lifetime=8h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_MAD_nuke_${dateTAG}_MnvTune_v2_VtxFix_noNeutronCuts_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_VtxFix_06132022.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh playlist_6A_data_Sept_2021_merged.txt playlist_6A_nuke_runs_126000_126100_June_2021_merged.txt 1 2 Targets "\"noNeutCuts\"" 0

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=6GB --disk=10GB --expected-lifetime=8h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_MAD_nuke_${dateTAG}_MnvTune_v2_VtxFix_wNeutronCuts_neutKE_10_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_VtxFix_06132022.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh playlist_6A_data_Sept_2021_merged.txt playlist_6A_nuke_runs_126000_126100_June_2021_merged.txt 1 2 Targets

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=6GB --disk=10GB --expected-lifetime=8h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_MAD_nuke_${dateTAG}_MnvTune_v1_VtxFix_noNeutronCuts_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_VtxFix_06132022.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh playlist_6A_data_Sept_2021_merged.txt playlist_6A_nuke_runs_126000_126100_June_2021_merged.txt 1 1 Targets "\"noNeutCuts\"" 0

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=6GB --disk=10GB --expected-lifetime=8h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_MAD_nuke_${dateTAG}_MnvTune_v1_VtxFix_wNeutronCuts_neutKE_10_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_VtxFix_06132022.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh playlist_6A_data_Sept_2021_merged.txt playlist_6A_nuke_runs_126000_126100_June_2021_merged.txt 1 1 Targets

### VTX binning fix and return to full recoil ranges###
#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=6GB --disk=10GB --expected-lifetime=8h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_MAD_nuke_${dateTAG}_MnvTune_v2_FullPreRecoil_noNeutronCuts_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_FullPreRecoil_06162022.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh playlist_6A_data_Sept_2021_merged.txt playlist_6A_nuke_runs_126000_126100_June_2021_merged.txt 1 2 Targets "\"noNeutCuts\"" 0

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=6GB --disk=10GB --expected-lifetime=8h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_MAD_nuke_${dateTAG}_MnvTune_v2_FullPreRecoil_wNeutronCuts_neutKE_10_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_FullPreRecoil_06162022.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh playlist_6A_data_Sept_2021_merged.txt playlist_6A_nuke_runs_126000_126100_June_2021_merged.txt 1 2 Targets

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=6GB --disk=10GB --expected-lifetime=8h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_MAD_nuke_${dateTAG}_MnvTune_v1_FullPreRecoil_noNeutronCuts_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_FullPreRecoil_06162022.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh playlist_6A_data_Sept_2021_merged.txt playlist_6A_nuke_runs_126000_126100_June_2021_merged.txt 1 1 Targets "\"noNeutCuts\"" 0

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=6GB --disk=10GB --expected-lifetime=8h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_MAD_nuke_${dateTAG}_MnvTune_v1_FullPreRecoil_wNeutronCuts_neutKE_10_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_FullPreRecoil_06162022.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh playlist_6A_data_Sept_2021_merged.txt playlist_6A_nuke_runs_126000_126100_June_2021_merged.txt 1 1 Targets

### FIXED SYSTEMATICS FOR TARGET ###
#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=4500MB --disk=2GB --expected-lifetime=24h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_MAD_nuke_${dateTAG}_MnvTune_v2_FixedSyst_noNeutronCuts_wSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_FixedSyst_06292022.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh playlist_6A_data_Sept_2021_merged.txt playlist_6A_nuke_runs_126000_126100_June_2021_merged.txt 0 2 Targets "\"noNeutCuts\"" 0

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=4500MB --disk=2GB --expected-lifetime=10h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_MAD_nuke_${dateTAG}_MnvTune_v2_FixedSyst_wNeutronCuts_neutKE_10_wSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_FixedSyst_06292022.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh playlist_6A_data_Sept_2021_merged.txt playlist_6A_nuke_runs_126000_126100_June_2021_merged.txt 0 2 Targets

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=4500MB --disk=2GB --expected-lifetime=24h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_MAD_nuke_${dateTAG}_MnvTune_v1_FixedSyst_noNeutronCuts_wSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_FixedSyst_06292022.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh playlist_6A_data_Sept_2021_merged.txt playlist_6A_nuke_runs_126000_126100_June_2021_merged.txt 0 1 Targets "\"noNeutCuts\"" 0

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=4500MB --disk=2GB --expected-lifetime=10h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_MAD_nuke_${dateTAG}_MnvTune_v1_FixedSyst_wNeutronCuts_neutKE_10_wSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_FixedSyst_06292022.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh playlist_6A_data_Sept_2021_merged.txt playlist_6A_nuke_runs_126000_126100_June_2021_merged.txt 0 1 Targets

### TESTING 6B FOR ABBEY CHANGES ###
#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=6GB --disk=2GB --expected-lifetime=24h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_MAD_tracker_${dateTAG}_MnvTune_v1_AbbeyTest_noNeutronCuts_wSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_AbbeyTest_07062022.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh AbbeyChanges_6B_data.txt AbbeyChanges_6B_tracker.txt 0 1 Tracker "\"noNeutCuts\"" 0

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=4GB --disk=2GB --expected-lifetime=4h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_MAD_tracker_${dateTAG}_MnvTune_v1_AbbeyTest_noNeutronCuts_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_AbbeyTest_07062022.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh AbbeyChanges_6B_data.txt AbbeyChanges_6B_tracker.txt 1 1 Tracker "\"noNeutCuts\"" 0

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=6GB --disk=2GB --expected-lifetime=24h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_MAD_tracker_${dateTAG}_MnvTune_v1_AbbeyTest_wNeutronCuts_wSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_AbbeyTest_07062022.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh AbbeyChanges_6B_data.txt AbbeyChanges_6B_tracker.txt 0 1 Tracker

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=4GB --disk=2GB --expected-lifetime=4h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_MAD_tracker_${dateTAG}_MnvTune_v1_AbbeyTest_wNeutronCuts_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_AbbeyTest_07062022.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh AbbeyChanges_6B_data.txt AbbeyChanges_6B_tracker.txt 1 1 Tracker

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=6GB --disk=2GB --expected-lifetime=24h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_MAD_tracker_${dateTAG}_MnvTune_v1_P1_6B_noNeutronCuts_wSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_AbbeyTest_07062022.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh P1_playlist_6B_data.txt P1_playlist_6B_tracker.txt 0 1 Tracker "\"noNeutCuts\"" 0

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=4GB --disk=2GB --expected-lifetime=4h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_MAD_tracker_${dateTAG}_MnvTune_v1_P1_6B_noNeutronCuts_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_AbbeyTest_07062022.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh P1_playlist_6B_data.txt P1_playlist_6B_tracker.txt 1 1 Tracker "\"noNeutCuts\"" 0

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=6GB --disk=2GB --expected-lifetime=24h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_MAD_tracker_${dateTAG}_MnvTune_v1_P1_6B_wNeutronCuts_wSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_AbbeyTest_07062022.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh P1_playlist_6B_data.txt P1_playlist_6B_tracker.txt 0 1 Tracker

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=4GB --disk=2GB --expected-lifetime=4h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_MAD_tracker_${dateTAG}_MnvTune_v1_P1_6B_wNeutronCuts_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_AbbeyTest_07062022.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh P1_playlist_6B_data.txt P1_playlist_6B_tracker.txt 1 1 Tracker

### W/O SYST FOR DEVELOPMENT OF WORK ###
#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=4GB --disk=2GB --expected-lifetime=8h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_MAD_tracker_${dateTAG}_MnvTune_v1_FullBreakdowns_wNeutronCuts_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_FullBreakdowns_2022_07_19.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh playlist_6B_data_July_2022_merged.txt playlist_6B_tracker_July_2022_merged.txt 1 1 Tracker

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=4GB --disk=2GB --expected-lifetime=8h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_MAD_tracker_${dateTAG}_MnvTune_v1_FullBreakdowns_noNeutronCuts_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_FullBreakdowns_2022_07_19.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh playlist_6B_data_July_2022_merged.txt playlist_6B_tracker_July_2022_merged.txt 1 1 Tracker "\"noNeutCuts\"" 0

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=4GB --disk=2GB --expected-lifetime=8h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_MAD_nuke_${dateTAG}_MnvTune_v1_FullBreakdowns_wNeutronCuts_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_FullBreakdowns_2022_07_19.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh playlist_6B_data_July_2022_merged.txt playlist_6B_nuke_July_2022_merged.txt 1 1 Targets

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=4GB --disk=2GB --expected-lifetime=8h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_MAD_nuke_${dateTAG}_MnvTune_v1_FullBreakdowns_noNeutronCuts_noSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_FullBreakdowns_2022_07_19.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh playlist_6B_data_July_2022_merged.txt playlist_6B_nuke_July_2022_merged.txt 1 1 Targets "\"noNeutCuts\"" 0

### TgtByTgt W/ SYST FOR DEVELOPMENT OF WORK ###
#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=6GB --disk=2GB --expected-lifetime=15h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_MAD_6A_tracker_${dateTAG}_MnvTune_v1_TgtByTgt_wNeutronCuts_wSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_TgtByTgt_2022_07_21_Tgt5Fix.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh playlist_6A_data_July_2022_merged.txt playlist_6A_tracker_July_2022_merged.txt 0 1 Tracker -1

#for var in {1..5}
#do
#    jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=6GB --disk=2GB --expected-lifetime=8h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_MAD_6A_nuke_${dateTAG}_MnvTune_v1_TgtByTgt_Tgt$var\_wNeutronCuts_wSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_TgtByTgt_2022_07_21_Tgt5Fix.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh playlist_6A_data_July_2022_merged.txt playlist_6A_nuke_July_2022_merged.txt 0 1 Targets $var
#done

#    jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=6GB --disk=2GB --expected-lifetime=8h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_MAD_6A_nuke_${dateTAG}_MnvTune_v1_TgtByTgt_WaterTgt_wNeutronCuts_wSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_TgtByTgt_2022_07_21_Tgt5Fix.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh playlist_6A_data_July_2022_merged.txt playlist_6A_nuke_July_2022_merged.txt 0 1 Targets 6

### TgtByTgt W/ Neutron Angle out of curiosity ###
#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=6GB --disk=2GB --expected-lifetime=18h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_MAD_6A_tracker_${dateTAG}_MnvTune_v1_NeutronAngleTest_wNeutronCuts_wSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_NeutronAngle_NoTruth_2022_07_28.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh playlist_6A_data_July_2022_merged.txt playlist_6A_tracker_July_2022_merged.txt 0 1 Tracker -1

#for var in {1..5}
#for var in {4..4}
#do
#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=6GB --disk=2GB --expected-lifetime=16h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_MAD_6A_nuke_${dateTAG}_MnvTune_v1_NeutronAngleTest_Tgt$var\_wNeutronCuts_wSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_NeutronAngle_NoTruth_2022_07_28.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh playlist_6A_data_July_2022_merged.txt playlist_6A_nuke_July_2022_merged.txt 0 1 Targets $var
#done

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=6GB --disk=2GB --expected-lifetime=8h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_MAD_6A_nuke_${dateTAG}_MnvTune_v1_NeutronAngleTest_WaterTgt_wNeutronCuts_wSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_NeutronAngle_NoTruth_2022_07_28.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh playlist_6A_data_July_2022_merged.txt playlist_6A_nuke_July_2022_merged.txt 0 1 Targets 6

### TgtByTgt w/ RecoilSideBand Instead of PreRecoilCut. ###
#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=6GB --disk=2GB --expected-lifetime=18h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_MAD_6A_tracker_${dateTAG}_MnvTune_v1_FlatRecoilSideband_500MeV_wNeutronCuts_wSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_FlatRecoilSideband_500MeV_2022_07_29.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh playlist_6A_data_July_2022_merged.txt playlist_6A_tracker_July_2022_merged.txt 0 1 Tracker -1

#for var in {1..5}
#do
    #jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=6GB --disk=2GB --expected-lifetime=16h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_MAD_6A_nuke_${dateTAG}_MnvTune_v1_FlatRecoilSideband_500MeV_Tgt$var\_wNeutronCuts_wSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_FlatRecoilSideband_500MeV_2022_07_29.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh playlist_6A_data_July_2022_merged.txt playlist_6A_nuke_July_2022_merged.txt 0 1 Targets $var
#done

#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=6GB --disk=2GB --expected-lifetime=8h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_MAD_6A_nuke_${dateTAG}_MnvTune_v1_FlatRecoilSideband_500MeV_WaterTgt_wNeutronCuts_wSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_FlatRecoilSideband_500MeV_2022_07_29.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh playlist_6A_data_July_2022_merged.txt playlist_6A_nuke_July_2022_merged.txt 0 1 Targets 6

### TgtByTgt w/ RecoilSideBand Instead of PreRecoilCut. ###
#jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=6GB --disk=2GB --expected-lifetime=18h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_MAD_6A_tracker_${dateTAG}_MnvTune_v1_NeutAngle_WithLeadBlobType_wNeutronCuts_wSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_NeutAngleUpdated_2022_08_01.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh playlist_6A_data_July_2022_merged.txt playlist_6A_tracker_July_2022_merged.txt 0 1 Tracker -1

#for var in {1..5}
#do
#    jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=6GB --disk=2GB --expected-lifetime=16h -N 1 -d OUT /pnfs/minerva/scratch/users/dlast/MyANA_MAD_6A_nuke_${dateTAG}_MnvTune_v1_NeutAngle_WithLeadBlobType_Tgt$var\_wNeutronCuts_wSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/dlast_NeutAngleUpdated_2022_08_01.tgz file:///minerva/app/users/dlast/TargetNeutronsAna/runEventLoop_job.sh playlist_6A_data_July_2022_merged.txt playlist_6A_nuke_July_2022_merged.txt 0 1 Targets $var
#done
#TODO: NEED TO MAKE TARBALL BEFORE SUBMISSION
jobsub_submit --group minerva -role=Analysis --resource-provides=usage_model=DEDICATED,OPPORTUNISTIC --memory=6GB --disk=2GB --expected-lifetime=16h -N 1 -d OUT /pnfs/minerva/scratch/users/sultana/MyANA_MAD_me1A_${dateTAG}_MnvTune_v1_150MichelCut_WithClusterEavail_Tracker_pTCut_wSYST -e IFDH_CP_MAX_RETRIES=1 -f /pnfs/minerva/resilient/tarballs/sultana_NeutAngleUpdated_2022_08_01.tgz file:///minerva/app/users/sultana/TargetNeutronsAna/runEventLoop_job.sh playlist_6A_data_July_2022_merged.txt playlist_6A_nuke_July_2022_merged.txt 0 1 Targets 6
